name: Backend Deployment

on:
    push:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Running Python unittest
            run: |
                echo running python tests!

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploying to AWS
            run: |
                echo deploying serverless app
