name: Deploy

on:
    push:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                pip3 install --upgrade setuptools
                pip3 install -r requirements-dev.txt
            - name: Run Python unittest
              run: python3 -m unittest discover tests/
              
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - name: Install dependencies
              run: npm ci
            - name: Serverless Deploy
              uses: jackdcasey/github-action@python3.8-nodejs13
              with:
                args: --stage prod deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: us-east-1
