name: Backend Deployment

on:
    push:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./py-lambdafunc
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                pip3 install -r requirements.txt
              working-directory: ${{env.working-directory}}
            - name: Setup local DynamoDB
              uses: rrainn/dynamodb-action@v2.0.0
              with:
                port: 8000
                cors: '*'
            - name: Running Python unittest
              run: |
                python3 -m unittest tests.py
              working-directory: ${{env.working-directory}}

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
              run: npm ci
            - name: Serverless Deploy
              uses: serverless/github-action@master
              with:
                args: --stage prod deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: us-east-1
